USE GrandVirusEpicenter;


/* CONSULTA #01 */
SELECT HOSPITAL.hospital_name, HOSPITAL.location, COUNT(VICTIM.death_date) AS Numero_de_fallecidos
FROM VICTIM_STUDIED
INNER JOIN HOSPITAL ON VICTIM_STUDIED.hospital_id = HOSPITAL.hospital_id
INNER JOIN VICTIM ON VICTIM_STUDIED.victim_id = VICTIM.victim_id
GROUP BY HOSPITAL.hospital_name, HOSPITAL.location
ORDER BY HOSPITAL.hospital_name;


/* CONSULTA #02 */
SELECT VICTIM.victim_name, VICTIM.surname 
FROM VICTIM_TREATMENT
INNER JOIN VICTIM ON VICTIM_TREATMENT.victim_id = VICTIM.victim_id
INNER JOIN TREATMENT ON VICTIM_TREATMENT.treatment_id = TREATMENT.treatment_id
INNER JOIN STATE ON VICTIM.state_id = STATE.state_id
WHERE VICTIM_TREATMENT.effect > 5 AND TREATMENT.tname = 'Transfusiones de sangre'AND
STATE.state_name = 'En cuarentena';

/* CONSULTA #03 */
SELECT VICTIM.victim_name, VICTIM.surname, VICTIM.location, COUNT(associated_id) AS Allegados
FROM ASSOCIATED_VICTIM 
INNER JOIN VICTIM ON ASSOCIATED_VICTIM.victim_id = VICTIM.victim_id 
WHERE VICTIM.death_date IS NOT NULL
GROUP BY VICTIM.victim_name, VICTIM.surname, VICTIM.location
HAVING COUNT(associated_id) > 3; 

/* CONSULTA #04 */

SELECT VICTIM.victim_name, VICTIM.surname
FROM ASSOCIATED_DETAIL
INNER JOIN ASSOCIATED_VICTIM ON ASSOCIATED_DETAIL.assvictim_id = ASSOCIATED_VICTIM.assvictim_id
INNER JOIN VICTIM ON ASSOCIATED_VICTIM.victim_id = VICTIM.victim_id 
INNER JOIN STATE ON VICTIM.state_id = STATE.state_id
INNER JOIN TYPE_CONTACT ON ASSOCIATED_DETAIL.type_id = TYPE_CONTACT.type_id
WHERE TYPE_CONTACT.type_name = 'Beso' AND STATE.state_name = 'Sospecha' 
GROUP BY VICTIM.victim_name, VICTIM.surname
HAVING COUNT(ASSOCIATED_VICTIM.associated_id) > 2;

/* CONSULTA #05 ***************************************/ 
SELECT VICTIM.victim_name, VICTIM.surname, COUNT(TREATMENT.tname) AS record
FROM VICTIM_TREATMENT
INNER JOIN VICTIM ON VICTIM_TREATMENT.victim_id = VICTIM.victim_id
INNER JOIN TREATMENT ON VICTIM_TREATMENT.treatment_id = TREATMENT.treatment_id
WHERE tname = 'Oxigeno'
GROUP BY VICTIM.victim_name, VICTIM.surname
ORDER BY record DESC
LIMIT 5;

/* CONSULTA #06 */

SELECT VICTIM.victim_name, VICTIM.surname, VICTIM.death_date
FROM VICTIM_TREATMENT
INNER JOIN VICTIM ON VICTIM_TREATMENT.victim_id = VICTIM.victim_id
INNER JOIN TREATMENT ON VICTIM_TREATMENT.treatment_id = TREATMENT.treatment_id
WHERE VICTIM.victim_id IN (SELECT victim_id FROM VICTIM_LOCATION WHERE location = '1987 Delphine Well') 
AND TREATMENT.tname = 'Manejo de la presion arterial';

/*SELECT VICTIM.victim_name, VICTIM.surname, VICTIM.death_date
FROM VICTIM_TREATMENT
INNER JOIN VICTIM ON VICTIM_TREATMENT.victim_id = VICTIM.victim_id
INNER JOIN TREATMENT ON VICTIM_TREATMENT.treatment_id = TREATMENT.treatment_id
WHERE  TREATMENT.tname = 'Manejo de la presion arterial';


SELECT VICTIM.victim_id , VICTIM.victim_name, VICTIM.surname
FROM VICTIM_LOCATION
INNER JOIN VICTIM ON VICTIM_LOCATION.victim_id = VICTIM.victim_id
WHERE VICTIM_LOCATION.location = '1987 Delphine Well';*/

/* CONSULTA #07 */
SELECT VICTIM.victim_name, VICTIM.surname, VICTIM.location
FROM ASSOCIATED_VICTIM 
INNER JOIN VICTIM ON ASSOCIATED_VICTIM.victim_id = VICTIM.victim_id 
WHERE (SELECT COUNT(TREATMENT.treatment_id) 
FROM VICTIM_TREATMENT
INNER JOIN TREATMENT ON VICTIM_TREATMENT.treatment_id = TREATMENT.treatment_id
WHERE victim_id = ASSOCIATED_VICTIM.victim_id
GROUP BY victim_id) = 2
GROUP BY VICTIM.victim_name, VICTIM.surname, VICTIM.location
HAVING COUNT(associated_id) < 2; 

/*
SELECT COUNT(TREATMENT.treatment_id) 
FROM VICTIM_TREATMENT
INNER JOIN TREATMENT ON VICTIM_TREATMENT.treatment_id = TREATMENT.treatment_id
GROUP BY victim_id;
*/

/* CONSULTA #08 */

SELECT VICTIM.sospecha_date, VICTIM.victim_name, VICTIM.surname, COUNT(VICTIM_TREATMENT.treatment_id) AS record
FROM VICTIM_TREATMENT
INNER JOIN VICTIM ON VICTIM_TREATMENT.victim_id = VICTIM.victim_id
INNER JOIN TREATMENT ON VICTIM_TREATMENT.treatment_id = TREATMENT.treatment_id
GROUP BY VICTIM.sospecha_date, VICTIM.victim_name, VICTIM.surname
HAVING COUNT(VICTIM_TREATMENT.treatment_id) = 
(SELECT MAX(maximo) FROM (
SELECT COUNT(VICTIM_TREATMENT.treatment_id) as maximo
FROM VICTIM_TREATMENT
INNER JOIN VICTIM ON VICTIM_TREATMENT.victim_id = VICTIM.victim_id
GROUP BY VICTIM.sospecha_date, VICTIM.victim_name, VICTIM.surname
) AS COUNTS2) OR 
COUNT(VICTIM_TREATMENT.treatment_id) = 
(SELECT MIN(minimo) FROM (
SELECT COUNT(VICTIM_TREATMENT.treatment_id) as minimo
FROM VICTIM_TREATMENT
INNER JOIN VICTIM ON VICTIM_TREATMENT.victim_id = VICTIM.victim_id
GROUP BY VICTIM.sospecha_date, VICTIM.victim_name, VICTIM.surname
) AS COUNTS) 
ORDER BY record DESC;

/*SELECT MAX(maximo) FROM (
SELECT COUNT(VICTIM_TREATMENT.treatment_id) as maximo
FROM VICTIM_TREATMENT
INNER JOIN VICTIM ON VICTIM_TREATMENT.victim_id = VICTIM.victim_id
GROUP BY VICTIM.sospecha_date, VICTIM.victim_name, VICTIM.surname
) AS COUNTS;

SELECT MIN(minimo) FROM (
SELECT COUNT(VICTIM_TREATMENT.treatment_id) as minimo
FROM VICTIM_TREATMENT
INNER JOIN VICTIM ON VICTIM_TREATMENT.victim_id = VICTIM.victim_id
GROUP BY VICTIM.sospecha_date, VICTIM.victim_name, VICTIM.surname
) AS COUNTS;*/

/* CONSULTA #09 */

SELECT HOSPITAL.hospital_name, COUNT(victim_id) as Cantidad, CONCAT((COUNT(victim_id) /(SELECT COUNT(victim_id) FROM VICTIM_STUDIED)*100),'%') AS Porcentaje
FROM VICTIM_STUDIED
INNER JOIN HOSPITAL ON VICTIM_STUDIED.hospital_id = HOSPITAL.hospital_id
GROUP BY HOSPITAL.hospital_name;

/* CONSULTA #10 */
SELECT HOSPITAL.hospital_name, TYPE_CONTACT.type_name,  COUNT(TYPE_CONTACT.type_name)
FROM VICTIM_STUDIED
INNER JOIN HOSPITAL ON VICTIM_STUDIED.hospital_id = HOSPITAL.hospital_id
INNER JOIN VICTIM ON VICTIM_STUDIED.victim_id = VICTIM.victim_id
INNER JOIN ASSOCIATED_VICTIM ON VICTIM.victim_id = ASSOCIATED_VICTIM.victim_id
INNER JOIN ASSOCIATED_DETAIL ON  ASSOCIATED_VICTIM.assvictim_id = ASSOCIATED_DETAIL.assvictim_id
INNER JOIN TYPE_CONTACT ON ASSOCIATED_DETAIL.type_id = TYPE_CONTACT.type_id
GROUP BY HOSPITAL.hospital_name, TYPE_CONTACT.type_name;

/****/
SELECT Nombre, MAX(Record) FROM
(SELECT HOSPITAL.hospital_name AS Nombre, TYPE_CONTACT.type_name AS Tipo,  COUNT(TYPE_CONTACT.type_name) AS Record
FROM VICTIM_STUDIED
INNER JOIN HOSPITAL ON VICTIM_STUDIED.hospital_id = HOSPITAL.hospital_id
INNER JOIN VICTIM ON VICTIM_STUDIED.victim_id = VICTIM.victim_id
INNER JOIN ASSOCIATED_VICTIM ON VICTIM.victim_id = ASSOCIATED_VICTIM.victim_id
INNER JOIN ASSOCIATED_DETAIL ON  ASSOCIATED_VICTIM.assvictim_id = ASSOCIATED_DETAIL.assvictim_id
INNER JOIN TYPE_CONTACT ON ASSOCIATED_DETAIL.type_id = TYPE_CONTACT.type_id
GROUP BY HOSPITAL.hospital_name, TYPE_CONTACT.type_name)
AS Total
WHERE Nombre = 'Animas General Hospital'
GROUP BY Nombre;






SELECT HOSPITAL.hospital_name, TYPE_CONTACT.type_name, SUM(COUNT(TYPE_CONTACT.type_name))
FROM VICTIM_STUDIED
INNER JOIN HOSPITAL ON VICTIM_STUDIED.hospital_id = HOSPITAL.hospital_id
INNER JOIN VICTIM ON VICTIM_STUDIED.victim_id = VICTIM.victim_id
INNER JOIN ASSOCIATED_VICTIM ON VICTIM.victim_id = ASSOCIATED_VICTIM.victim_id
INNER JOIN ASSOCIATED_DETAIL ON  ASSOCIATED_VICTIM.assvictim_id = ASSOCIATED_DETAIL.assvictim_id
INNER JOIN TYPE_CONTACT ON ASSOCIATED_DETAIL.type_id = TYPE_CONTACT.type_id
GROUP BY HOSPITAL.hospital_name, TYPE_CONTACT.type_name;





SELECT * FROM VICTIM_TREATMENT ;
SELECT * FROM TREATMENT ;
SELECT * FROM VICTIM;
SELECT * FROM STATE;
SELECT * FROM TYPE_CONTACT;

-- 6

/*SELECT HOSPITAL.hospital_name, HOSPITAL.location, VICTIM.death_date, VICTIM.victim_name, surname
FROM VICTIM_STUDIED
INNER JOIN HOSPITAL ON VICTIM_STUDIED.hospital_id = HOSPITAL.hospital_id
INNER JOIN VICTIM ON VICTIM_STUDIED.victim_id = VICTIM.victim_id
WHERE HOSPITAL.hospital_name = 'Archangel Clinic';*/

